-- UDE: Auto-Discovered Theorems
-- Verified by Lean 4
-- Generated by Universal Discovery Engine

import Init

namespace UDE

theorem reflexive_eq : ∀x : Nat, x = x := by
  intro x
  rfl

theorem symmetric_eq : ∀x y : Nat, x = y → y = x := by
  intros x y h
  rw [h]

theorem transitive_eq : ∀x y z : Nat, x = y → y = z → x = z := by
  intros x y z h1 h2
  rw [h1, h2]

theorem and_intro : ∀p q : Prop, p → q → p ∧ q := by
  intros p q hp hq
  constructor
  exact hp
  exact hq

theorem or_intro_left : ∀p q : Prop, p → p ∨ q := by
  intros p q h
  exact Or.inl h

theorem or_intro_right : ∀p q : Prop, q → p ∨ q := by
  intros p q h
  exact Or.inr h

theorem or_elim : ∀p q r : Prop, (p ∨ q) → (p → r) → (q → r) → r := by
  intros p q r h hpr hqr
  cases h with | inl hp => exact hpr hp | inr hq => exact hqr hq

theorem implies_intro : ∀p q : Prop, (p → q) → p → q := by
  intros p q h hp
  exact h hp

theorem not_false : ¬False := by
  intro h
  cases h

theorem ex_falso : ∀p : Prop, False → p := by
  intros p h
  cases h

theorem double_neg_intro : ∀p : Prop, p → ¬¬p := by
  intros p h np
  apply np h

theorem contraposition : ∀p q : Prop, (p → q) → (¬q → ¬p) := by
  intros p q h nq hp
  apply nq
  exact h hp

theorem true_or_false : True ∨ False := by
  exact Or.inl True.intro

end UDE